backend:
  name: github
  repo: whmountains/wings-patagonia-data
  branch: master

media_folder: "uploads" # Folder where user uploaded files should go

collections: # A list of collections the CMS should be able to edit
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/home.md"
        label: "Home"
        name: "home"
        fields:
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: Accent Button, name: cta, widget: string}
          - {label: Video Button, name: video, widget: string}
          - {label: Scroll Prompt, name: scrollPrompt, widget: string}
